service: serverless-sample

frameworkVersion: '3'

provider:
  name: aws
  runtime: java8
  region: eu-central-1

package:
  artifact: target/sls-sample-dev.jar

functions:
  myFirstLambda:
    handler: com.serverless.Handler
